FT.manifest({
	"filename":"index.html",
	"width":970,
	"height":418,
  "clickTagCount":1,
  "expand":{
    "fullscreen":false,
    "width":970,
    "height":418,
    "indentAcross":670,
    "indentDown":0
  }
});